import { Composition, registerRoot } from 'remotion';
import { ChessVideo } from './ChessVideo';

// Attempt to read the saved moves file generated by the frontend
let savedData: any = { moveList: [], initialFen: undefined };
try {
  const data = require('../../moves.json');
  if (Array.isArray(data)) {
    savedData = { moveList: data, initialFen: undefined };
  } else {
    savedData = data;
  }
} catch (e) {
  savedData = { moveList: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6'], initialFen: undefined }; // fallback
}

export const RemotionRoot: React.FC = () => {
  const { moveList, initialFen, moveEvents } = savedData;
  
  const fps = 30;
  // 22 seconds * 30 fps = 660 frames
  const durationInFrames = 660;

  return (
    <>
      <Composition
        id="MyChessVideo"
        component={ChessVideo}
        durationInFrames={durationInFrames}
        fps={fps}
        width={1080}
        height={1920}
        defaultProps={{
          moveList,
          initialFen,
          moveEvents
        }}
      />
    </>
  );
};

registerRoot(RemotionRoot);
