import { Composition, registerRoot } from 'remotion';
import '../app/globals.css';
import { ChessVideo } from './ChessVideo';

// Attempt to read the saved moves file generated by the frontend
let savedData: any = { moveList: [], initialFen: undefined };
try {
  const data = require('../../moves.json');
  if (Array.isArray(data)) {
    savedData = { moveList: data, initialFen: undefined };
  } else {
    savedData = data;
  }
} catch (e) {
  savedData = { moveList: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6'], initialFen: undefined }; // fallback
}

export const RemotionRoot: React.FC = () => {
  const { moveList, initialFen } = savedData;
  
  const fps = 30;
  // Ensure the video is at least 20 seconds (600 frames)
  // We use 2.0s (60 frames) per move + 3 seconds of padding
  const durationInFrames = Math.max((moveList.length * 60) + (fps * 3), 600);

  return (
    <>
      <Composition
        id="MyChessVideo"
        component={ChessVideo}
        durationInFrames={durationInFrames}
        fps={fps}
        width={1080}
        height={1920}
        defaultProps={{
          moveList,
          initialFen
        }}
      />
    </>
  );
};

registerRoot(RemotionRoot);
